Document: libtwitcurl
Title: Debian libtwitcurl Manual
Author: <insert document author here>
Abstract: This manual describes what libtwitcurl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libtwitcurl/libtwitcurl.sgml.gz

Format: postscript
Files: /usr/share/doc/libtwitcurl/libtwitcurl.ps.gz

Format: text
Files: /usr/share/doc/libtwitcurl/libtwitcurl.text.gz

Format: HTML
Index: /usr/share/doc/libtwitcurl/html/index.html
Files: /usr/share/doc/libtwitcurl/html/*.html
